### ISSUE TITLE
Expose function for determining a PRs status to a library

### ISSUE THREAD

**Issue by uncenter** [getchoo/nixpkgs-tracker-bot#20]
Would be nice to be able to pull in the logic for determining a PR's status outside of just the context of Discord. Could even be a CLI?

**Comment by getchoo** [comment]
See [crates/git-tracker](https://github.com/getchoo/nixpkgs-tracker-bot/tree/76f25523a65fa01755a125dca566dcda30e08090/crates/git-tracker)

I don't  intend to publish this on crates.io as it's pretty limited to just what we do here and I would rather not maintain it as a public library -- but it could easily be re-used outside of the Discord commands

**Comment by uncenter** [comment]
Sure but that is a generic libgit2 wrapper right? It isn't specific to tracking Nixpkgs.

**Comment by getchoo** [comment]
It is; but what I was referring to as "niche" is how it is a handful of specific purpose functions mainly geared towards using data from the GitHub API. I don't know how many others would really want to re-use this (tracking a commit between branches is niche as-is) or have a good experience with it. Either way, it might not even be worth it considering how [light](https://github.com/getchoo/nixpkgs-tracker-bot/blob/76f25523a65fa01755a125dca566dcda30e08090/crates/git-tracker/src/tracker.rs#L39-L41) many of these abstractions are

I would also just want to note that this was never designed with public consumption even in mind, just internal re-use in case I ever make a Matrix, etc version
